### ISSUE TITLE
Nom du plugin

### ISSUE THREAD

**Issue by davidmaignan** [LAEQ/q3m#1]
Suggestion de nom pour le plugin.
1. dois etre recherchable 
2. unique
3. Anglo/franco

**Comment by JojoGelb** [comment]
J'ajoute que le nom ne doit pas contenir plugin:
https://plugins.qgis.org/publish/
Voici une proposition:
QGIS User Friendly MapMatching

**Comment by davidmaignan** [comment]
MapMatching ? MapMatching_laeq

**Comment by JojoGelb** [comment]
MapMatching_laeq me va. Je pense qu'il sera possible de le changer plus tard si une autre idée nous vient à l'esprit

**Comment by davidmaignan** [comment]
Ok j'ai opté pour LAEQ-MapMatching car il y a un autre plugin avec le nom Offline-MapMatching (plus raccord pour pour la recherche).
