### ISSUE TITLE
Convention pour definir les clés traduction 

### ISSUE THREAD

**Issue by davidmaignan** [LAEQ/q3m#10]
@JojoGelb . Il faut choisir une convention pour définir des clés uniques pour les textes.

Eg: q3m.section.subsection.status|id|action

L'idée c'est d'être suffisamment élaboré (couvrir tous les cas) tout en restant simple. Bonus facilement retrouvable avec un grep -r.

```python
self.create_message_error("No network layer detected, makes sure the layer is active in the layer tab  : Refresh?", "Refresh", Qgis.Critical)
```
q3m.network_layer.button.refresh: Refresh
q3m.network_layer.error.invalid: No network layer detected, makes sure the layer is active in the layer tab: Refresh ?

```python
# first.py
self.create_message_error(self.tr("q3m.network_layer.error.invalid"), self.tr("q3m.network_layer.button.refresh"), Qgis.Critical)

# autre fichier: ajoute une methode 
def tr(message : str) -> str:
   return message

# On ajoutera le reste du code plus tard (QCoreApplication.translate('MapMatching', message) + config + generation des  fichiers
```

C'est aussi valable pour pour les images
section.image_titre.url = images/path/image_en.png

Pour info les fichiers avec les traductions seront dans i18n: 
- MapMatching_en.qm
- MapMatching_fr.qm
- MapMatching_zh.qm

```
<message>
        <location filename="../map_matching.py" line="166"/>
        <source>q3m.network_layer.error.invalid</source>
        <translation>No network layer detected, makes sure the layer is active in the layer tab: Refresh ?</translation>
</message>
```

**Comment by JojoGelb** [comment]
Ok, c'est intéressant. Donc basiquement créer un dossier avec les fichiers de traductions et selon le paramètre donné par l'utilisateur, chercher ces traductions qui seront à la même place mais dans différents fichiers. Faudrait-il précharger tous les messages à l'ouverture du plugin / sélection du langage ou on fait des recherches dans le fichier à la volée pour obtenir les messages qui nous intéressent?
Je propose également de créer un dossier ressource dans le main contenant les dossiers image, i18n et toute autre ressources qui pourraient nous être utile plus tard

**Comment by davidmaignan** [comment]
Pour répondre à plusieurs points. 
1. Le dossier existe dans master: i18n
2. Création des fichiers: c'est automatique avec Qt (QLinguist). [HELP.MD](https://github.com/LAEQ/q3m/blob/unitttest/HELP.md) (branche unitttest).
3. Gestion/chargement voir [test/test_translation.py - test_gqis_translations](https://github.com/LAEQ/q3m/blob/unitttest/test/test_translations.py). 
4. Fiichier principale (first.py pour ta branche et map_matching.py pour main): utilise la méthode self.tr (tr means translation, I guess)
5. Autre fichier:  ajouter une methode tr et retourne la clé (on ajoutera la logique + tard) (translation service ou helper)
6. Le changement de locale est géré par Qgis (settings > options > general).

**Comment by davidmaignan** [comment]
oui pour dossier ressource

**Comment by davidmaignan** [comment]
As tu un suggestion pour la convention de nommage ?

**Comment by JojoGelb** [comment]
La convention de nommage des ressources/fichier ou des clés?
Pour les fichiers je propose comme tu as fait jusque la: Majuscule au début et _ entre le mots: ex: Test_ressources.jpg
Pour ce qui est des clés je propose de les garder à un minimum de mot possible.

**Comment by JojoGelb** [comment]
Les systèmes de transport des erreurs ainsi que de traduction sont fonctionnels. Les messages sont stocké dans le dossier i18n.
