### ISSUE TITLE
Paramètres avancés

### ISSUE THREAD

**Issue by JeremyGelb** [LAEQ/q3m#14]
Plusieurs de nos fonctions utilisent des paramètres que l'on a actuellement fixés, par exemple : 
- vitesse minimale en dessous de laquelle on consdière que l'on est à l'arrêt,
- tolérance topologique
- tolérance pour l'algorithme de map-matching
- ...

Je me demande si on ne pourrait pas laisser une utilisateur avancé fixer ces valeurs dans un panneau du plugin qui serait caché par défaut et que l'on pourrait afficher en cliquant sur une flèche pour dérouler le menu en question

**Comment by davidmaignan** [comment]
Il n'est pas trop difficile de faire une deuxieme fenetre pour centraliser et modifier ces parametres.
1. Creer un classe Settings (instancier dans map_matching.py __init__) avec des valeurs default.
2. Creer un fichier ui avec qt creator pour le layout
3. Creer un classe python pour generer la fenetre + injection de la classe Settings.
4. Ajout bouton dans fenetre pour ouvrir la fenetre reglage

Question: Si les modifs doivent  etre conserver entre les sessions (fermeture/ouverture qgis, ou reload du plugin, ...). sauvegarde dans un fichier (~/.local/share/QGIS/QGIS3/profiles/default/q3m_settings.json)

**Comment by JojoGelb** [comment]
On peut en effet faire ça. Je recommande cependant d'utiliser l'objet de qtCreator tabWidget qui permet de créer plusieurs tabs/fenetres au sein d'un même ui. Cela permet d'éviter d'avoir plusieurs fenêtres.
Pour ce qui est de la classe Settings, cela va surement dépendre du nombre de paramètres que l'on peut rentrer dans les fonctions. Pour le moment, nous en avons que trois. Je ne pense pas nécessaire de créer une classe. On pourrait récupérer les valeurs inscrites dans  ce second tab lors de l'appel d'une des méthodes qui en a besoin et les envoyer au travers des fonctions.

**Comment by davidmaignan** [comment]
Oui pour la tab/fenêtre.

Pour la classe settings:
1. centraliser les valeurs et les fournir aux autres services (via injection)
2. implementer la logique pour la sauvegarde et lecture dans un fichier de config
3. Pouvoir écrire des tests unitaires

**Comment by JojoGelb** [comment]
Settings ajoutés et fonctionnels
