### ISSUE TITLE
Organisation de l'interface graphique

### ISSUE THREAD

**Issue by JojoGelb** [LAEQ/q3m#15]
Pour le moment, notre interface graphique ressemble à ceci:
![image](https://user-images.githubusercontent.com/65153333/118094404-fa5d8580-b3ce-11eb-8de3-2bd595f6a128.png)

Je propose de déplacer le champ de vitesse dans la partie de matching afin que l'utilisateur ne fasse pas d'aller retour entre les boites

**Comment by JeremyGelb** [comment]
Je suis d'accord avec la proposition de deplacer le menu deroulant vitesse
