### ISSUE TITLE
Style des notations du projet

### ISSUE THREAD

**Issue by JojoGelb** [LAEQ/q3m#3]
Comment nommons nous les variables-fonctions-classes du projet?
Je propose:
Classe: UpperKamelCase
Méthode: lowerKamelCase
Variables: text_sep_by_tiret8

Il faut aussi faire en sorte de ne pas faire d'abréviation afin de garder le code lisible et facilement compréhensible.

**Comment by JeremyGelb** [comment]
Je trouve cette convention acceptable, @davidmaignan ?

**Comment by davidmaignan** [comment]
Je pensais que l'on suivait PEP8.

https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables 

Use the function naming rules: lowercase with words separated by underscores as necessary to improve readability.
Use one leading underscore only for non-public methods and instance variables.

classe: UpperKamelCase
methode: lower_kamel_case
variable: test_sep_by_tiret_8

**Comment by davidmaignan** [comment]
Voice le modèle à suivre: https://gist.github.com/RichardBronosky/454964087739a449da04

**Comment by JeremyGelb** [comment]
Nice, merci bcp, j'avais pas assé lu en détail le document !
