### ISSUE TITLE
mode Batch

### ISSUE THREAD

**Issue by JeremyGelb** [LAEQ/q3m#9]
Comme suggéré par Philippe, la première partie des traitements (sous-sélection et correction topologique) sont un peu couteuse en temps de calcul et ne requiert pas d'action de la part de l'usager. Il serait intéressant d'envisager un mode batch pour toutes les effectuer dans un premiers temps sur un ensemble de traces.

**Comment by JojoGelb** [comment]
Mode batch abandonné à cause de la nature même du plugin. Le processus étant trop "instable" selon le réseau de route souvent incomplet, il est préférable que l'utilisateur fasse ses modifications manuellement un à un. De plus le plugin est plutôt rapide.
